# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples
force_color_prompt=yes

# Color working directory blue, prompt char red
PS1='\[\e[34m\]\w\[\e[0m\] \[\e[0;32m\]\[\e[0m\]\[\e[1;31m\]\$\[\e[0m\] '

# use bash completion if available:
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

# keep more history
export HISTFILESIZE=100000
export HISTSIZE=9999
shopt -s histappend
# Ignore duplicates, ls without options and builtin commands
export HISTCONTROL=ignoredups
export HISTIGNORE="history:ls:pwd:exit:ll:la:clear"
# Timestamp the history entries
export HISTTIMEFORMAT="%b %d %R "

# General shell settings:
source ~/.profile

# Brightcove:
source ~/.brightcoverc

# Secrets:
source ~/.secrets
