# vim: set filetype=zsh :

#
# ZSH Setup
#

# warp directory (https://github.com/mfaerevaag/wd)
wd () {
    . $HOME/ws/repos/wd/wd.sh
}
# warp directory completions:
fpath=($HOME/ws/repos/wd $fpath)
# zsh completions from homebrew:
if [ -d /usr/local/share/zsh/site-functions ]; then
    . /usr/local/share/zsh/site-functions
fi

autoload -Uz compinit colors add-zsh-hook
compinit -u     # autocomplete
colors          # colors
typeset -U PATH # no dupes in PATH

export PATH="$HOME/gd/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH"

gstat () {
    if test -d ".git"; then
        psvar[1]=" `git rev-parse --abbrev-ref HEAD`"
        psvar[2]=`git diff-index --quiet HEAD -- || echo "*"`
    else
        psvar[1]=""
        psvar[2]=""
    fi
}
# get git meta-information periodically, every 1s
PERIOD=1
add-zsh-hook periodic gstat
# prompt format
PROMPT="%{$fg[blue]%}%4~%{$fg[green]%}%1v%{$fg[red]%}%2v%{$fg_bold[red]%} %# %{$reset_color%}"

HISTFILE=~/.zsh_history                            # where to store zsh config
HISTSIZE=7500                                      # lines of history to keep in mem
SAVEHIST=30000                                     # lines of history to save to file
HISTORY_IGNORE="(history|ls|pwd|exit|ll|la|clear)" # commands history ignores

setopt APPEND_HISTORY           # append
setopt HIST_IGNORE_DUPS         # no duplicate
setopt HIST_IGNORE_ALL_DUPS     # no duplicate
setopt HIST_REDUCE_BLANKS       # trim blanks
setopt SHARE_HISTORY            # share hist between sessions
setopt HIST_IGNORE_SPACE        # ignore commands prefixed by a space
setopt HIST_NO_STORE            # dont store dupes
setopt BANG_HIST                # !keyword
setopt NO_BEEP                  # no terminal beeps
setopt HIST_SAVE_NO_DUPS        # more de-duping
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS
setopt INTERACTIVECOMMENTS      # recognize comments on cli
setopt NO_COMPLETE_ALIASES      # autocomplete aliases, this seems to do the opposite of what it sounds like

# completion
zstyle ':completion:*' menu select
# oh-my-zsh style history completion
bindkey '\e[A' history-beginning-search-backward
bindkey '\e[B' history-beginning-search-forward
bindkey '\e[3~' delete-char # 'forward' delete key

# Cross-shell settings:
source ~/.rc

# Secrets:
source ~/.secrets

# Amazon:
source ~/.amazonrc
