#
# ZSH Setup
#

# warp directory (https://github.com/mfaerevaag/wd)
wd () {
    . $HOME/ws/repos/wd/wd.sh
}
# warp directory completions:
fpath=($HOME/ws/repos/wd $fpath)

autoload -Uz compinit colors
compinit -u     # autocomplete
colors          # colors
typeset -U PATH # no dupes in PATH

export PATH="$HOME/gd/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH"

# completion
zstyle ':completion:*' menu select
setopt COMPLETE_ALIASES
# oh-my-zsh style history completion
bindkey '\e[A' history-beginning-search-backward
bindkey '\e[B' history-beginning-search-forward

# prompt format
PROMPT="%{$fg[blue]%}%4~ %{$fg_bold[red]%}%# %{$reset_color%}%{$fg[white]%}"

HISTFILE=~/.zsh_history                            # where to store zsh config
HISTSIZE=7500                                      # lines of history to keep in mem
SAVEHIST=100000                                    # lines of history to save to file
HISTORY_IGNORE="(history|ls|pwd|exit|ll|la|clear)" # commands history ignores

setopt APPEND_HISTORY           # append
setopt HIST_IGNORE_ALL_DUPS     # no duplicate
setopt HIST_REDUCE_BLANKS       # trim blanks
setopt SHARE_HISTORY            # share hist between sessions
setopt BANG_HIST                # !keyword
unsetopt HIST_IGNORE_SPACE      # ignore space prefixed commands

# Cross-shell settings:
source ~/.rc

# Brightcove:
source ~/.brightcoverc

# Secrets:
source ~/.secrets
